name: cloud_firestore_odm_generator
version: 1.0.0-dev.1

environment:
  sdk: ">=2.14.0-0.0.dev <3.0.0"

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.1
  build_config: ^1.0.0
  cloud_firestore_odm: ^1.0.0-dev.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0

  # So we can run dart tests in the melos workspace - otherwise dart test will
  # source the package from pub - which won't have the local changes (or is not yet published).
  cloud_firestore_odm:
    path: ../cloud_firestore_odm

  expect_error: ^1.0.0
  json_serializable: ^5.0.0
  matcher: ^0.12.10
  test: ^1.16.8
